# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html
import everforest
everforest.set(c, 'dark', 'medium') # options are dark/light and hard/medium/soft

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(True)
